### ISSUE TITLE
dup `remove_dita_table_row_column_seps`

### ISSUE THREAD

**Issue by AirQuick** [oxygenxml/dita-refactoring-examples#6]
These two dirs have duplicate files:
- https://github.com/oxygenxml/dita-refactoring-examples/tree/master/34%20Remove%20All%20Separators
- https://github.com/oxygenxml/dita-refactoring-examples/tree/master/removeTableRowColSeps

Incidentally, these dirs have the same `34 ` prefix in their names:
- https://github.com/oxygenxml/dita-refactoring-examples/tree/master/34%20Change%20Prefix%20in%20MathML%20Equation%20for%20DITA%20topics
- https://github.com/oxygenxml/dita-refactoring-examples/tree/master/34%20Remove%20All%20Separators

**Comment by raducoravu** [comment]
@AirQuick thanks for that, I removed the "removeTableRowColSeps" folder and then renamed the duplicate "34" folder to "39 Remove All Table Separators".
I had this idea of using numbers in front of the folder names so that they would show up in a certain order in the Oxygen project view for a presentation I gave. Idea which I'm starting to regret :)
